PromptMain: "如果你是一个临床实验研究人员，根据统计标准检查输入报告是否符合要求，并只输出报告中没有符合统计标准的部分。统计标准如下："
StatStandards:
  标题页: 
  - 研究标题/编号/版本/日期  
  - 符合标准声明ICH E9(R1)  
  - 申办方/主要研究者签名  
  结构化摘要: 
  - 研究目的  
  - 主要/次要终点  
  - 研究方法（设计类型/样本量）  
  - 关键结果（效应量+95%CI）  
  - 结论 
  引言: 
  - 疾病背景与未满足需求  
  - 试验药物机制  
  - 研究科学依据 
  研究目标与假设: 
  - 主要目标（与估计目标对齐）  
  - 次要目标  
  - 统计假设（H0/H1公式）
  研究设计: 
    试验设计:
    - 类型（随机/双盲/平行）  
    - 治疗周期/随访安排
    随机化与盲法:
    - 随机化方法（分层因素/区组大小）
    - 盲法实施细节
    研究流程图:
  统计学方法:
    估计目标定义:
      - 治疗策略（如何处理停药/补救治疗）
      - 目标人群（详细入排标准）
      - 终点变量（主要终点定义）
      - 伴发事件处理（如"使用补救药物=失败"）
      - 群体总结（统计模型（如Cox模型））
    样本量计算: 公式/参数
    分析数据集:
      - 全分析集（FAS）定义  
      - 符合方案集（PPS）定义  
      - 安全性集（SS）定义
    统计模型:
      - 主要终点分析方法（如MMRM）  
      - 协变量调整计划
    缺失数据处理:
      - 主要方法（如多重插补）  
      - 敏感性分析计划
    多重性控制:
      - 检验顺序图/校正方法 
  研究人群:
    受试者流程图:
    基线特征表:
      - 所有预设分层因素  
      - 组间比较
  有效性结果:
    主要终点分析:
      - 效应量（HR/RR/OR）  
      - 95%置信区间  
      - p值（保留3位小数） 
    次要终点分析:
      - 多重性控制说明
    敏感性分析:
      - 不同缺失数据处理
      - 不同估计目标策略
    亚组分析:
      - 预设亚组结果（森林图）
  安全性结果:
    治疗暴露:
    不良事件汇总: 任何AE/≥3级AE/导致停药AE 
    严重不良事件列表:
  讨论:
    - 结果与估计目标一致性  
    - 临床意义解读  
    - 局限性（缺失数据/亚组分析）  
    - 偏倚风险评估
  结论:
    - 主要发现总结  
    - 风险获益评估
  参考文献:
    - ICH E9(R1)指南  
    - 统计方法参考文献  
  附录(关键合规文件):
    - 附录A(签字版统计分析计划（SAP） )
    - 附录B(伦理批准文件)  
    - 附录C(数据监查委员会（DMC）报告)  
    - 附录D(主要统计代码（SAS/R）) 
    - 附录E(病例报告表（CRF）样本页) 
    - 附录F(估计目标详细定义框架) 

  

    
  
